from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    AIChatView,
    AIFinancialIntelligenceView,
    BudgetViewSet,
    CategoryViewSet,
    ChangePasswordView,
    CsrfView,
    FinancialAccountViewSet,
    LoginView,
    LogoutView,
    MeView,
    MonoCreateDemoAccountView,
    MonoExchangeView,
    MonoInitiateView,
    MonoTestWebhookView,
    MonoWebhookView,
    NotificationsView,
    RegisterView,
    SavingsGoalViewSet,
    TransactionViewSet,
)

router = DefaultRouter()
router.register(r"categories", CategoryViewSet, basename="category")
router.register(r"accounts", FinancialAccountViewSet, basename="financialaccount")
router.register(r"transactions", TransactionViewSet, basename="transaction")
router.register(r"budgets", BudgetViewSet, basename="budget")
router.register(r"goals", SavingsGoalViewSet, basename="savingsgoal")

urlpatterns = [
    # Utility
    path("csrf/", CsrfView.as_view(), name="csrf"),
    # Auth
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/change-password/", ChangePasswordView.as_view(), name="auth-change-password"),
    # Notifications
    path("notifications/", NotificationsView.as_view(), name="notifications"),
    # AI
    path("ai/chat/", AIChatView.as_view(), name="ai-chat"),
    path("ai/financial-intelligence/", AIFinancialIntelligenceView.as_view(), name="ai-financial-intelligence"),
    # Mono
    path("mono/initiate/", MonoInitiateView.as_view(), name="mono-initiate"),
    path("mono/webhook/", MonoWebhookView.as_view(), name="mono-webhook"),
    path("mono/test-webhook/", MonoTestWebhookView.as_view(), name="mono-test-webhook"),
    path("mono/create-demo/", MonoCreateDemoAccountView.as_view(), name="mono-create-demo"),
    path("mono/exchange/", MonoExchangeView.as_view(), name="mono-exchange"),  # Fixed
    # Resource endpoints (auto-generated by the router)
    path("", include(router.urls)),
]
