from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    BudgetViewSet,
    CategoryViewSet,
    FinancialAccountViewSet,
    LoginView,
    LogoutView,
    MeView,
    RegisterView,
    SavingsGoalViewSet,
    TransactionViewSet,
)

router = DefaultRouter()
router.register(r"categories", CategoryViewSet, basename="category")
router.register(r"accounts", FinancialAccountViewSet, basename="financialaccount")
router.register(r"transactions", TransactionViewSet, basename="transaction")
router.register(r"budgets", BudgetViewSet, basename="budget")
router.register(r"goals", SavingsGoalViewSet, basename="savingsgoal")

urlpatterns = [
    # Auth
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    # Resource endpoints (auto-generated by the router)
    path("", include(router.urls)),
]
